#pragma line 1 "edge_prj/main.c" ::: -10
#pragma line 1 "edge_prj/main.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 296 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 3
#pragma line 8 "<command line>" 2 ::: 119
#pragma line 1 "<built-in>" 2 ::: 120
#pragma line 1 "edge_prj/main.c" 2 ::: 121
#pragma line 1 "edge_prj/sobel.h" 1 ::: 122
#pragma line 2 "edge_prj/main.c" 2 ::: 130
#pragma line 1 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\ap_cint.h" 1 ::: 131
#pragma line 62 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\ap_cint.h" ::: 132
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 133
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 142
#pragma line 10 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 143
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 144
#pragma line 10 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 145
#pragma line 277 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 146
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 147
#pragma line 13 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 148
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 149
#pragma line 674 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 150
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 151
#pragma line 674 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 152
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 154
#pragma line 675 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 155
#pragma line 13 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 156
#pragma line 102 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 176
#pragma line 277 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 178
#pragma line 370 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 182
#pragma line 380 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 184
#pragma line 392 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 186
#pragma line 405 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 188
#pragma line 418 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 190
#pragma line 428 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 192
#pragma line 456 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 203
#pragma line 607 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 223
#pragma line 9 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 285
#pragma line 36 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 3 ::: 286
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 1 3 ::: 427
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 436
#pragma line 9 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 2 3 ::: 437
#pragma line 175 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 438
#pragma line 63 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\ap_cint.h" 2 ::: 439
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 440
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 449
#pragma line 9 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 450
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 453
#pragma line 11 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 454
#pragma line 26 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 458
#pragma line 84 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 470
#pragma line 120 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 489
#pragma line 157 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 491
#pragma line 312 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 637
#pragma line 330 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 645
#pragma line 373 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 681
#pragma line 417 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 716
#pragma line 475 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 746
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 782
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 791
#pragma line 9 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 792
#pragma line 509 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 793
#pragma line 1 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 796
#pragma line 511 "E:/vivado174/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 797
#pragma line 64 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\ap_cint.h" 2 ::: 798
#pragma line 77 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\ap_cint.h" ::: 799
#pragma line 1 "E:/vivado174/Vivado/2017.4/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 800
#pragma line 57 "E:/vivado174/Vivado/2017.4/common/technology/autopilot/etc/autopilot_apint.h" ::: 801
#pragma line 1 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt.h" 1 ::: 802
#pragma line 97 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt.h" ::: 803
#pragma line 1 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 804
#pragma line 98 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 1843
#pragma line 1 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 1844
#pragma line 99 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 2871
#pragma line 108 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt.h" ::: 2872
#pragma line 1 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 2873
#pragma line 109 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 3912
#pragma line 1 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 3913
#pragma line 110 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 4940
#pragma line 131 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_dt.h" ::: 4941
#pragma line 58 "E:/vivado174/Vivado/2017.4/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 4944
#pragma line 1 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" 1 ::: 4945
#pragma line 59 "E:/vivado174/Vivado/2017.4/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 4946
#pragma line 78 "E:/vivado174/Vivado/2017.4/common/technology/autopilot\\ap_cint.h" 2 ::: 4947
#pragma line 3 "edge_prj/main.c" 2 ::: 4948
#pragma line 39 "edge_prj/main.c" ::: 4987
#pragma line 40 "edge_prj/main.c" ::: 4991
#pragma line 52 "edge_prj/main.c" ::: 5006
#pragma line 54 "edge_prj/main.c" ::: 5011
#pragma line 76 "edge_prj/main.c" ::: 5036
#pragma line 77 "edge_prj/main.c" ::: 5040
