// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _convolution_HH_
#define _convolution_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct convolution : public sc_module {
    // Port declarations 6
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<3> > p_read;
    sc_in< sc_lv<4> > p_read2;
    sc_in< sc_lv<32> > p_read3;
    sc_in< sc_lv<32> > p_read5;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    convolution(sc_module_name name);
    SC_HAS_PROCESS(convolution);

    ~convolution();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<32> > tmp_15_fu_48_p0;
    sc_signal< sc_lv<3> > tmp_15_fu_48_p1;
    sc_signal< sc_lv<32> > tmp_15_fu_48_p2;
    sc_signal< sc_lv<32> > tmp_15_2_fu_60_p0;
    sc_signal< sc_lv<4> > tmp_15_2_fu_60_p1;
    sc_signal< sc_lv<32> > tmp_1_fu_54_p2;
    sc_signal< sc_lv<32> > tmp_15_2_fu_60_p2;
    sc_signal< sc_lv<32> > tmp_2_fu_72_p2;
    sc_signal< sc_lv<32> > tmp_fu_66_p2;
    sc_signal< sc_lv<32> > tmp1_fu_78_p2;
    sc_signal< sc_lv<32> > tmp_15_2_fu_60_p10;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return();
    void thread_tmp1_fu_78_p2();
    void thread_tmp_15_2_fu_60_p0();
    void thread_tmp_15_2_fu_60_p1();
    void thread_tmp_15_2_fu_60_p10();
    void thread_tmp_15_2_fu_60_p2();
    void thread_tmp_15_fu_48_p0();
    void thread_tmp_15_fu_48_p1();
    void thread_tmp_15_fu_48_p2();
    void thread_tmp_1_fu_54_p2();
    void thread_tmp_2_fu_72_p2();
    void thread_tmp_fu_66_p2();
};

}

using namespace ap_rtl;

#endif
